### ISSUE TITLE
Frequent "The access token has been expired" dismounts

### ISSUE THREAD

**Issue by ggambier** [rooey/chromeos-filesystem-onedrive#13]
Access to my OneDrive works well, but only for a short length of time (not yet determined). After the aforementioned short time, a system notification pops up saying "The access token has been expired. File system unmounted". I can mount the drive again as many times as I like, but the above recurs.

**Comment by jamesiinsf** [comment]
I have the same experience. It is frustrating, especially with 2 step security turned on.

**Comment by Donostio** [comment]
Same here. It would be great if you could fix it. Any plans/possibility? Thank you.

**Comment by rockman73** [comment]
I can reproduce this problem as well. Extremely useful app, thank you for it! It's just marginally useful and could be a killer app for the Chrome OS.

**Comment by rockman73** [comment]
OK, after a quick review of closed issues, this is a known issue which appears the developer cannot solve without the API changing.

https://github.com/yoichiro/chromeos-filesystem-onedrive/issues/10
