### ISSUE TITLE
OneDrive for Business Support

### ISSUE THREAD

**Issue by electrify12** [rooey/chromeos-filesystem-onedrive#15]
The Onedrive file system support does not support OneDrive for Business accounts. That functionality would be beneficial to have.

**Comment by Entry92** [comment]
This issue is what prevents me from having this app installed, as I do not personally use OneDrive, though it is what my school uses. It would be convenient to have a filesystem mount to my school account.

**Comment by Richardvi** [comment]
Exactly the same here. Many schools use for example Chromebooks in combination with Office 365. This plugin would help them a lot, but unfortunately the OneDrive for Business is not supported.

Is there any chance this will change in the future?

**Comment by rooey** [comment]
Added in new fork: https://github.com/rooey/chromeos-filesystem-onedrive

**Comment by tjebb** [comment]
This is actually not really fixed. The tool needs permission to access admin resources, which user accounts don’t have, thereby noy providing support for 99% of the organization.. Hope it can be fixed, thanks :)
