### ISSUE TITLE
OneDrive does not seem to mount properly

### ISSUE THREAD

**Issue by ndguardian** [rooey/chromeos-filesystem-onedrive#16]
Upon trying to mount OneDrive on my Chromebook, I am getting error messages saying "Some operations are taking longer than expected. Do you want to abort them?" Rebooting, reinstalling, etc does not seem to resolve the issue.

**Comment by TimBennettUK** [comment]
Hi. I get the same issue with trying to mount OneDrive on my Chromebook.  Any suggestions on how to overcome this please?

**Comment by Donostio** [comment]
This is also happening to me. Any plans to fix it please? App is disabled for now.

**Comment by sh0ume1sa1** [comment]
me too

**Comment by bmeacham** [comment]
I have the same problem with brand new Acer R11 Chromebook.  Some operations are taking longer than expected. Do you want to abort them?"  Here is my Chrome OS version information.

Version 54.0.2840.101 (64-bit)
Platform 8743.85.0 (Official Build) stable-channel cyan
ARC Version 3487238
Firmware Google_Cyan.7287.57.82
