### ISSUE TITLE
plugin fails after just a few minutes after launching - getting delay notifications

### ISSUE THREAD

**Issue by Telegadget** [rooey/chromeos-filesystem-onedrive#22]
Hello!

Using personal version of OneDrive. Using my chromebook, I was using this plugin and it was working for a while. Now when I launch it from the Files app, it loads but then starts sending me 'application taking too long....' notifications and sends these notifications continuously.  Also cant click on the Onedrive folder in the Folders app. Have to end the plugin to stop the notifications.

**Comment by rooey** [comment]
#23 duplicated report
