### ISSUE TITLE
One Drive Error.  App is lagging/unresponsive

### ISSUE THREAD

**Issue by hurricane2368** [rooey/chromeos-filesystem-onedrive#24]
Receiving the error from the OneDrive file system app.  After mounting, receive the following pop up alert: "An operation is taking longer than expected.  Do you want to abort it?"  Then I have to abort that process.  Been seeing this issue for about 2 weeks or so,  Below is the output from the Developer Console.

Start: assignEventHandlers
background.js:1306 End: assignEventHandlers
_generated_background_page.html:1 Error in response to storage.get: TypeError: Cannot read property 'refreshToken' of undefined
    at OneDriveFS.<anonymous> (chrome-extension://jbfdfcehgafdbfpniaimfbfomafoadgo/background.js:1055:53)
    at OneDriveFS.resume (chrome-extension://jbfdfcehgafdbfpniaimfbfomafoadgo/background.js:1050:34)
    at OneDriveFS.<anonymous> (chrome-extension://jbfdfcehgafdbfpniaimfbfomafoadgo/background.js:1214:22)

**Comment by phillym** [comment]
Duplicate of #23

**Comment by SZE2** [comment]
@phillym I don't think this is a duplicate.

I'm getting this issue on a Personal Onedrive account as well.

**Comment by phillym** [comment]
Hi @SZE2 !

Yes, I appreciate OD and OfB are different technologies but the error above is identical. #23 is probably two separate issues:
1. Token issue as posted here in #24
2. CORS issue as posted in subsequent update to #23 

Problem being, neither of these tickets have been even acknowledged :(

**Comment by rooey** [comment]
I'm not sure what's causing this. I've seen it on some other operations too. Will need to debug.

**Comment by rooey** [comment]
Will address this with #23
