### ISSUE TITLE
Getting Abort message constantly

### ISSUE THREAD

**Issue by GaaraPrime** [rooey/chromeos-filesystem-onedrive#25]
It won't run. Constantly told it isn't responding, and to Abort. I think I've seen this posted elsewhere. 

Is there a fix coming soon? Is there a paid version that will resolve this issue (don't mind paying for the app it works).

Cheers.

**Comment by dmcgitit** [comment]
I am having this issue as well, it was working perfectly yesterday when I installed it, until I shut my chromebook down and restarted. Please advise!

**Comment by logan-markewich** [comment]
Just got an asus C302 and am having the same issue as well. Haven't found a solution anywhere online :/

**Comment by dmcgitit** [comment]
I removed it, went with Google drive, no issues now

**Comment by logan-markewich** [comment]
Well when you have 1TB storage on onedrive, I'd rather use that lol

**Comment by rooey** [comment]
Duplicate of #23
