### ISSUE TITLE
Rewrite onedrive_client.js with correct API calls

### ISSUE THREAD

**Issue by rooey** [rooey/chromeos-filesystem-onedrive#31]
onedrive_client.js updates need to be fixed with the correct API URLs and calls for OneDrive.

**Comment by droz36** [comment]
Do you have any time coming up to work on rewriting this app? I would like to help with it.

**Comment by rooey** [comment]
I already did. I merged the changes to master last night. I'm having an issue with refresh after a copy from one directory to another and also thumbnail previews, otherwise it's working well.

**Comment by rooey** [comment]
Oh I haven't implemented refresh token yet either for persistent connections, so it unmounts automatically on expiry at the moment. Do you have your own valid API key?

**Comment by droz36** [comment]
I had an API key before. I haven't really looked at the code in a long time, but I can always set one up again if I need to.

**Comment by rooey** [comment]
Excellent. An additional permission is needed now for user.read other than that, it should be same as before

**Comment by rooey** [comment]
Implemented in 7e21d8cb8a6800e1a979ebf096bcc91fbf7e4188

**Comment by droz36** [comment]
i keep getting a failed to mount object. did I do something wrong?

**Comment by rooey** [comment]
Did you add the user.read to your ms graph API key?

**Comment by rooey** [comment]
or maybe i screwed up the build i checked in... hang on...

**Comment by rooey** [comment]
seems ok - don't forget to add your API secret

**Comment by droz36** [comment]
Yes. I did

**Comment by droz36** [comment]
What do you put in redirect url?

**Comment by rooey** [comment]
message on slack?
https://join.slack.com/t/chromiumdev/shared_invite/enQtMzM3NjYwNjI0MDM4LTk2NjEyYTIxODk1MDYxMmNjNWYzMGMxZGVhMDNhY2I1ZjBhMjdlYTg0MTg4ZGE0OTQ0ZmYwNTRiMGJlYzVjOTE

**Comment by rooey** [comment]
addressed in #044fb10
