### ISSUE TITLE
Implement createUploadSession - Support Larger Files

### ISSUE THREAD

**Issue by rooey** [rooey/chromeos-filesystem-onedrive#36]
createUploadSession is currently disabled; as this needs re-writing correctly for GRAPH API per:

- https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0

**Comment by droz36** [comment]
@rooey getMetaDataCache appears to hold the filesize. could it be stored as a var and passed into some type of decision making code that decides whether or not to start an upload session?

I think metadatatrim is replacing the actual filesize with a boolean. is that the case? Javascript is not a language i do work in on a regular basis
