### ISSUE TITLE
Failed to upload files in v3.0.0

### ISSUE THREAD

**Issue by wyudong** [rooey/chromeos-filesystem-onedrive#47]
**Describe the bug**

I'm compiling the latest code from [master](https://github.com/rooey/chromeos-filesystem-onedrive/commit/75dc0f38b6806ecdc2dfcf473e3dc725a597f80e) branch and install Version 3.0.0 Alpha - Build 04281 on a Chromebook. But it fails to upload files to OneDrive using this extension. However, viewing, downloading, deleting files are all OK. 

**To Reproduce**

Steps to reproduce the behaviour:
1. Drag a file from My files to OneDrive (this extension)
2. Error said "Copy operation failed. The file or the directory is no usable." at the sidebar
3. A 0-byte file is copied to OneDrive but the file is broken

**Expected behaviour**

It should upload files to OneDrive without any error.

**ChromeOS Version**
 - Version 76

**Additional context**
[Console.log](https://drive.google.com/file/d/1opo_h48PWIrRyy1x9hh4a_TXRLubTy36/view?usp=sharing). The format is sloppy but I think the problem is caused by a 400 request. I don't know how to set the parameter `itemId` in the url correctly. In the original code, it is replaced with `this` ([L611](https://github.com/rooey/chromeos-filesystem-onedrive/blob/75dc0f38b6806ecdc2dfcf473e3dc725a597f80e/src/scripts/onedrive_client.js#L611)).

```
https://graph.microsoft.com/v1.0/me/drive/items/onedrivefs://ad120d5f0a4630df/createUploadSession 400 (Bad Request)
```

**Comment by rooey** [comment]
This issue is covered in #39 and #36. The feature is still being written...

**Comment by rooey** [comment]
awesome that you managed to get it compiled and working tho.... Grats! :)
