### ISSUE TITLE
Chrome Web Store - missing? 404

### ISSUE THREAD

**Issue by iamacarpet** [rooey/chromeos-filesystem-onedrive#50]
The link to the Chrome Web Store in the README file returns a 404 and I can't find it anywhere in the store when searching manually.

Have Google removed it for some reason?

**Comment by rooey** [comment]
Yes, they removed it a few months back (after it had been there for years) citing that:

> it does not comply with our program policies. Please review this section of our policy:
> 
> Developers must not obfuscate code or conceal functionality of their extension. This also applies to any external code or resource fetched by the extension package.
> 
> Your item was found to have one or more files that does not comply with this policy.

They then ignored all subsequent requests for clarification/advice/information.

In all fairness, the code that was live at the time was awful; which is why I re-wrote it - but never managed to iron out the upload bug.  I simply haven't had time to finish it and no-one seems to care that it's gone.

It's worth noting that if you install the OneDrive Android app you will get read-only access to your OneDrive via "files" now.

**Comment by rooey** [comment]
You can join this group:
https://groups.google.com/forum/#!forum/chromeos-onedrive-testers
To get access to the pre-built Alpha page:
https://chrome.google.com/webstore/detail/file-system-for-onedrive/ceklkpjapeaemmdchpmdkoegdnfmagba

**Comment by iamacarpet** [comment]
Thanks for the update!

I think I fixed the upload & download bugs in One Drive for Business this afternoon (at-least both are working for me now), plus the folder creation issue.

I think tomorrow I want to take a look at making office documents open in Office Online rather than as files when you open them, a bit like how Google Docs files work in Google Drive File Stream on Windows - have a few ideas how to make this work, will let you know.

I’m going to publish our own version on the internal version of the Chrome Store (for our G Suite organisation only), but if my boss agrees to the sign up fee, would you mind if we publish it more widely?

**Comment by rooey** [comment]
If you commit the code change back we can test and re-release. Not sure what fee you're referring to.

**Comment by iamacarpet** [comment]
Sure, np. If you are happy to still be the publisher, that works for me.

I was referring to the $5 that you have to pay Google to be able to publish outside of your organisation in the Chrome Web Store.

**Comment by rooey** [comment]
No. it's nice to have someone else take a look. Fresh eyes and all that. I had pretty much given up...
