### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by naorlss** [rooey/chromeos-filesystem-onedrive#55]

**Comment by naorlss** [comment]
I have cloned the repository and try to start but it does not work:

It fails once I try the gulp command. I don't understand what I need to do to run the gulp command.

In addition, https://chrome.google.com/webstore/detail/file-system-for-onedrive/jbfdf
cehgafdbfpniaimfbfomafoadgo does not work.
It seems that this extension is no longer present in the webstore.

**Comment by naorlss** [comment]
I closed by mistake - please can you help me?

**Comment by rooey** [comment]
This is a development build, you need a development environment (linux or crostini shell) and follow the instructions provided here (https://github.com/rooey/chromeos-filesystem-onedrive) on how to build the tool. Once you've built it you need to copy the compiled version onto your system and install it. Your system would need to be in developer mode for that.

If you want to download the pre-compiled development/test (Alpha) version - you can join this group:
https://groups.google.com/forum/#!forum/chromeos-onedrive-testers
and  download from the webstore: 
https://chrome.google.com/webstore/detail/file-system-for-onedrive/ceklkpjapeaemmdchpmdkoegdnfmagba
