### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by codemonkey85** [rooey/chromeos-filesystem-onedrive#9]
I would appreciate multiple account support, so that I could mount both my personal and work accounts as separate drives.

**Comment by Manouchehri** [comment]
Came here to suggest the same thing, it'd be useful to have both personal and work drives. The Dropbox extension seems to support that.

**Comment by LordMethenor** [comment]
Could this please happen? Currently, I am using two accounts, one for school and one for personal. This will change in the future, but until then, I am stuck.

**Comment by alphonset69** [comment]
I believe I speak for many when I say that I am willing to pay for this application.  I suggest that you consider a base version, for free, then add a Pro version that includes support for multiple accounts.  A price of $4.99 is reasonable.  You may also consider looking for corporate sponsors.  There are more corporations that would welcome the opportunity to move people to a thin client that the Chromebook platform represents.

**Comment by rooey** [comment]
Foundation provided in 7e21d8cb8a6800e1a979ebf096bcc91fbf7e4188

**Comment by alphonset69** [comment]
I was able to build and run locally.  I have successfully mounted multiple OneDrive accounts.  Thank you!

**Comment by rooey** [comment]
BEWARE the bugs. this is FAR from stable right now.

**Comment by alphonset69** [comment]
Yes, I'm open to being an Alpha tester.  Let me know the next steps.

**Comment by rooey** [comment]
Just send me a valid google ID and i'll add you to the list :)

Probably best to do via slack? [Chromiumdev Slack](https://join.slack.com/t/chromiumdev/shared_invite/enQtMzM3NjYwNjI0MDM4LTk2NjEyYTIxODk1MDYxMmNjNWYzMGMxZGVhMDNhY2I1ZjBhMjdlYTg0MTg4ZGE0OTQ0ZmYwNTRiMGJlYzVjOTE)
